server:
  port: 5005
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
        defaultZone: http://eureka-server1:3001/eureka/
  instance:
    instance-id: Zuul路由服务-5005
zuul:
  routes:
    service-user:
        path: /api/user/**
        serviceId: service-user
        stripPrefix: false
    service-blog:
        path: /api/blog/**
        serviceId: service-blog
        stripPrefix: false
