server:
  port: 3001
eureka:
  instance:
    # 在服务中心显示的名称
    hostname: eureka-server1
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false声明是服务端
    fetch-registry: false
    service-url:
        # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
        defaultZone: http://eureka-server2:3002/eureka/
