server:
  port: 4002
spring:
  application:
    # 可根据自己的业务命名
    name: eureka-client
eureka:
  client:
    service-url:
        defaultZone: http://eureka-server1:3001/eureka/,http://eureka-server2:3002/eureka/
  instance:
    instance-id: 业务模块1-4002