server:
  port: 5004
spring:
  application:
    name: Hystrix-Feign
eureka:
  client:
    service-url:
        defaultZone: http://eureka-server1:3001/eureka/,http://eureka-server2:3002/eureka/
  instance:
    instance-id: Hystrix-Feign
feign:
  hystrix:
    enabled: true