server:
  port: 5007
spring:
  application:
    name: service-blog-5005
eureka:
  client:
    service-url:
        defaultZone: http://eureka-server1:3001/eureka/
  instance:
    instance-id: Service-Blog