server:
  port: 5006
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Liangshan1994/SpringCloud
          search-paths: SpringCloud-Config-Repo
          username:
          password:
eureka:
  client:
    service-url:
        defaultZone: http://eureka-server1:3001/eureka/
  instance:
    instance-id: 配置中心-5006