server:
  port: 5002
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
        defaultZone: http://eureka-server1:3001/eureka/,http://eureka-server2:3002/eureka/
  instance:
    instance-id: Feign
eureka-client:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule